version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_acidentes
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: metabase_app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./metabase_data:/metabase-data 
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    depends_on:
      - db

volumes:
  pgdata: